### PR TITLE
Various updates, including a fix to work on latest Julia master

### PR DESCRIPTION
**Pull request by garrison**
I made some changes to various things, but most importantly got the code to work on julia `master` again.  All tests pass, but in order to get `PyCall` to work I had to apply the changes in stevengj/PyCall.jl#124, which will hopefully be merged soon.  I also moved the test file so it would work by calling `Pkg.test` if `SJulia` is installed in `~/.julia/v0.4/SJulia`.

Feel free to cherry-pick if you do not like all the changes, or I'd be happy to separate into multiple pull requests.

### CODE REVIEW

**Comment by jlapeyre** [comment]
Thanks for the help. The changes all look useful. I just started a new job, so I haven't been able to pay much attention to the project recently. But, I'll pull the commits.

**Comment by jlapeyre** [comment]
I forgot that for over a month I have not been able build Julia. One of the common messages on failure is
`could not allocate pools`.  I need to get Julia working on some machine before I can test the changes.

**Comment by garrison** [comment]
Have you tried `make clean`, `make cleanall`, and/or a fresh checkout?

**Comment by jlapeyre** [comment]
Yes, I tried that and more. But, I just looked up the old thread and saw that someone found it was his `ulimit`. So now I'm on track again.

**Comment by jlapeyre** [comment]
Not quite yet ! `/bin/sh: 1: sphinx-build: not found`. Working on fixing this.

**Pull request merged**
